apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
  namespace: test
  labels:
    app: resume
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - name: resume
        image: 905418417758.dkr.ecr.us-east-1.amazonaws.com/resume:latest
        ports:
        - containerPort: 9028
